# 日志
logging:
  file:
    path: ./logs
  level:
    root: info
  config: classpath:logging-spring.xml

spring:
  # DataSource
  datasource:
    url: jdbc:mysql://10.10.2.217:32623/bum?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: bum
    password: m868P4Km0MLq5HWP
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 空闲时保持最小连接数
      minimum-idle: 20
      # 空闲连接存活时间 默认 10 分钟
      idle-timeout: 600000
      # 连接超时时间 默认 30s
      connection-timeout: 30000
      # 测试sql
      connection-test-query: select 1
  # Redisson
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: Parav1ew
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://10.10.2.217:32426"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
  # SpringCache
  cache:
    type: redis
    redis:
      time-to-live: 86400000
      cache-null-values: true
      key-prefix: 'example:'

